### ISSUE TITLE
Converting cp2k data to dp data

### ISSUE THREAD

**Issue by siddarthachar** [deepmodeling/dpdata#103]
Hello,

I have some simulations run on cp2k and was trying to train a DP-model from the AIMD data. While I tried converting the *pos*.xyz and *.log files to dp files, it ended up with this error.
`  File "cp2k-to-dp.py", line 2, in <module>
    g_out = dpdata.LabeledSystem("*", fmt = 'cp2k/aimd_output')
  File "/ihome/kjohnson/ska31/.virtualenvs/tensorflow/lib/python3.6/site-packages/dpdata-0.1.15-py3.6.egg/dpdata/system.py", line 945, in __init__
    self.from_fmt(file_name, fmt, type_map=type_map, begin= begin, step=step)
  File "/ihome/kjohnson/ska31/.virtualenvs/tensorflow/lib/python3.6/site-packages/dpdata-0.1.15-py3.6.egg/dpdata/system.py", line 134, in from_fmt
    func(self, file_name, **kwargs)
  File "/ihome/kjohnson/ska31/.virtualenvs/tensorflow/lib/python3.6/site-packages/dpdata-0.1.15-py3.6.egg/dpdata/system.py", line 999, in from_cp2k_aimd_output
    xyz_file=glob.glob("{}/*pos*.xyz".format(file_dir))[0]`

Is this a bug or has this code been make for a certain version of cp2k? 
The version that I am using is 6.1.

I did end up making changes to the source code and managed to convert these files to dp, however, there were no raw files created for forces. So I wasn't sure if my cp2k input scripts were correct. 

It would be great if you could:
1. Mention the version of cp2k to use (if there is no bug in the code)
2. Probably provide sample examples for cp2k (where the forces are accounted for)

Best, 
Sid

**Comment by robinzyb** [comment]
Hello siddarthachar,
The example file is under the `test/cp2k/aimd/` directory.
For first question: for the error, can you provide the file you have and let me make a test?
For second question: 
The force information is contained in the output file of cp2k.
In order to print this information, make sure that the `CP2K_INPUT / FORCE_EVAL / PRINT / FORCES` turns on

**Comment by siddarthachar** [comment]
Hello robinzyb,

Thanks a lot for such a quick response. I will be providing the following file: 
1. cp2k input 
2. *pos*.xyz
3. *.log

I do I think I have accounted for forces (that is force_eval) print in them. However it should give me the same error as earlier with forces as well.

[graphanol-111.zip](https://github.com/deepmodeling/dpdata/files/4745956/graphanol-111.zip)

Please let me know if these files are viewable.

**Comment by robinzyb** [comment]
Hi, 
I can't unzip the archive file
Maybe something lost ?
```
Archive:  graphanol-111.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of graphanol-111.zip or
        graphanol-111.zip.zip, and cannot find graphanol-111.zip.ZIP, period.
```

**Comment by siddarthachar** [comment]
Oh, I apologize. It must be a .rar file. Please could you check this file?

[graphane.zip](https://github.com/deepmodeling/dpdata/files/4746754/graphane.zip)

**Comment by robinzyb** [comment]
Hello, 
 I checked your `cp2k.inp`, force print section is not included. Hence, the log file doesn't have the force information either.
add the following into your input file
```
&FORCE_EVAL
       &PRINT                                                                    
     &FORCES ON                                                                  
     &END FORCES                                                                 
   &END PRINT
&END FORCE_EVAL     
```

-----------
Also, the error in your question `File "/ihome/kjohnson/ska31/.virtualenvs/tensorflow/lib/python3.6/site-packages/dpdata-0.1.15-py3.6.egg/dpdata/system.py", line 999, in from_cp2k_aimd_output xyz_file=glob.glob("{}/*pos*.xyz".format(file_dir))[0]`
If I guess right, there has a `IndexError: list index out of range` message after this error.
This is because the glob.glob function didn't find the file `*pos*.xyz`
It is highly possible that you specified a wrong path to directory that should contain the `pos.xyz` file

If the `pos.xyz` is under the directory `./aimd/`, the code should be
```
x = dpdata.LabeledSystem('aimd', fmt='cp2k/aimd_output')                        
x.to('deepmd/npy', 'dpmd_npy')   
```

**Comment by siddarthachar** [comment]
Hello,

I managed to run fix the issue. It works right now. Thanks a lot for your help. Appreciate it.

**Comment by SchrodingersCattt** [comment]
Hi,

May I ask whether there is a newer script to convert AIMD result from CP2K 2023 to dp? It seems that the readData_CP2K.py works perfectly for CP2K 7.1 but gives the following error.

`# the data contains 0 frames
Traceback (most recent call last):
  File "/home/haorui/GMY/MeHdabco_RbI3/cp2k2023test/readData_CP2K.py", line 12, in <module>
    data_training = data.sub_system(index_training)
  File "/home/haorui/.local/lib/python3.10/site-packages/dpdata/system.py", line 503, in sub_system
    new_shape = [slice(None) for _ in self.data[tt.name].shape]
AttributeError: 'list' object has no attribute 'shape'`

Best regards,
M.-Y.G.

**Comment by robinzyb** [comment]
refer to this https://github.com/robinzyb/cp2kdata/issues/15

**Comment by SchrodingersCattt** [comment]
Hello, 


Received. My problem is solved now.


Thank you very much!


Best regards,
M.Y.G.
















在 2023-09-07 18:59:20，"Yongbin Zhuang" ***@***.***> 写道：

refer to this robinzyb/cp2kdata#15

**Comment by chenyuping6** [comment]
Hello,

I have some simulations run on cp2k and was trying to train a DP-model from the AIMD data.I am using version cp2k7.1, and the dpdata version is the latest version. The folder is aimd, which contains my dynamics files. The command I entered is dp=dpdata LabeledSystem ('aimd test ', cp2k_outputtname="cp2k. out", fmt="cp2k/aimd_output"), but keeps reporting errors.I have provided my files. Can you help me check where the problem lies? If you reply, I would not be very grateful！
The content is as follows: Traceback (most recent call last):

File<stdin>, line 1, in<module>

File "/public/home/CYP/deepmd kit/lib/python3.11/site packages/dpdata/system. py", line 183, in__ Init__

Self. from_ Fmt（

File "/public/home/CYP/deepmd kit/lib/python3.11/site packages/dpdata/system. py", line 220, in from_ Fmt

Return self.from_ Fmt_ Obj (load_format (fmt), file_ Name, * * kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/public/home/CYP/deepmd kit/lib/python3.11/site packages/dpdata/system. py", line 1113, in from_ Fmt_ Obj

Data=fmtobj.from_ Labeled_ System (filename, * * kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/public/home/CYP/deepmd kit/lib/python3.11/site packages/dpdata/plugins/cp2k. py", line 21, in from_ Labeled_ System

Log_ File=sorted (global. blob (f "{filename}/*. log")) [0]

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^

IndexError: list index out of range
[aimd.zip](https://github.com/deepmodeling/dpdata/files/13859890/aimd.zip)

**Comment by chenyuping6** [comment]
Hello,

I have some simulations run on cp2k and was trying to train a DP-model from the AIMD data.I am using version cp2k7.1, and the dpdata version is the latest version. The folder is aimd, which contains my dynamics files. The command I entered is dp=dpdata LabeledSystem ('aimd ', cp2k_outputtname="cp2k. out", fmt="cp2k/aimd_output"), but keeps reporting errors. I have provided my files. Can you help me check where the problem lies? If you reply, I would be very grateful！
The content is as follows: Traceback (most recent call last):

File, line 1, in

File "/public/home/CYP/deepmd kit/lib/python3.11/site packages/dpdata/system. py", line 183, in__ Init__

Self. from_ Fmt（

File "/public/home/CYP/deepmd kit/lib/python3.11/site packages/dpdata/system. py", line 220, in from_ Fmt

Return self.from_ Fmt_ Obj (load_format (fmt), file_ Name, * * kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/public/home/CYP/deepmd kit/lib/python3.11/site packages/dpdata/system. py", line 1113, in from_ Fmt_ Obj

Data=fmtobj.from_ Labeled_ System (filename, * * kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/public/home/CYP/deepmd kit/lib/python3.11/site packages/dpdata/plugins/cp2k. py", line 21, in from_ Labeled_ System

Log_ File=sorted (global. blob (f "{filename}/*. log")) [0]

IndexError: list index out of range
[aimd.zip](https://github.com/deepmodeling/dpdata/files/13859954/aimd.zip)

**Comment by SchrodingersCattt** [comment]
Hi, yuping.

It seems that the filename of your CP2K output file is "output", so you might need to change the code to 
`LabeledSystem ('aimd ', cp2k_outputtname="output", fmt="cp2k/aimd_output")`

Here is a workable script:
`
import dpdata 
from cp2kdata import Cp2kOutput
import numpy as np

cp2kmd_dir = "."
cp2kmd_output_name = "output"
data = dpdata.LabeledSystem(cp2kmd_dir, cp2k_output_name=cp2kmd_output_name, fmt="cp2kdata/md")
print(data)

print('# the data contains %d frames' % len(data))

# random choose 40 index for validation_data
index_validation = np.random.choice(10,size=2,replace=False)
# other indexes are training_data
index_training = list(set(range(10))-set(index_validation))
data_training = data.sub_system(index_training)
data_validation = data.sub_system(index_validation)
# all training data put into directory:"training_data"
data_training.to_deepmd_npy('training_data')
# all validation data put into directory:"validation_data"
data_validation.to_deepmd_npy('validation_data')

print('# the training data contains %d frames' % len(data_training)) 
print('# the validation data contains %d frames' % len(data_validation)) 
print(data)
`

I hope this could help.

Best regards,
M.Y.G.

**Comment by chenyuping6** [comment]
Hello,
Thank you for your patient answer. I have tested the script you provided multiple times and installed cp2kdata, but there are still the following errors. Can you provide me with guidance? Thank you very much!
Traceback (most recent call last):
  File "/public/home/CYP/Au25/PA10/md/10ps/test.py", line 1, in <module>
    import dpdata
  File "/public/home/CYP/Au25/PA10/md/10ps/dpdata.py", line 3, in <module>
    data = dpdata.LabeledSystem('aimd ', cp2k_outputtname="output", fmt="cp2k/aimd_output")
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'dpdata' has no attribute 'LabeledSystem' (most likely due to a circular import)
English Translation:
In addition, if within a simulation task lasting a total of 10000 fs, one wishes to extract a structure every 100 fs, resulting in a total of 100 structures for dpgen simulation, how should the input file be configured?

**Comment by chenyuping6** [comment]
Hi
My problem has been solved. Thank you very much for patiently answering it.
Best regards
Yuping chen

**Comment by chenyuping6** [comment]
Hi
I am able to successfully convert the cp2k md file into a DP model using the scripts provided by the developers mentioned above. However, when I tried to convert it into a DPGEN input file, I still encountered an error. Can you help me see where the problem lies? Thank you very much！
--- You are parsing data using package Cp2kData ---
You are reading cell information from ./aimd/output
Obtian Energies From ./aimd/input-1.ener
Obtian Structures From ./aimd/input-pos-1.xyz
Obtian Froces From ./aimd/input-frc-1.xyz
Atom names are fake chemical symbols as you set in cp2k input.
--- You are parsing data using package Cp2kData ---
Data Summary
Labeled System
-------------------
Frame Numbers      : 21
Atom Numbers       : 489
Including Virials  : No
Element List       :
-------------------
Au  S  C  H
35  18  224  212
# the data contains 21 frames

**Comment by chenyuping6** [comment]
Hi
I am able to successfully convert the cp2k md file into a DP model using the scripts provided by the developers mentioned above. However, when I tried to convert it into a DPGEN input file, I still encountered an error. Can you help me see where the problem lies? Thank you very much！
--- You are parsing data using package Cp2kData ---
You are reading cell information from ./aimd/output
Obtian Energies From ./aimd/input-1.ener
Obtian Structures From ./aimd/input-pos-1.xyz
Obtian Froces From ./aimd/input-frc-1.xyz
Atom names are fake chemical symbols as you set in cp2k input.
--- You are parsing data using package Cp2kData ---
Data Summary
Labeled System
Frame Numbers : 21
Atom Numbers : 489
Including Virials : No
Element List :
Au S C H
35 18 224 212

the data contains 21 frames

**Comment by robinzyb** [comment]
> Hi I am able to successfully convert the cp2k md file into a DP model using the scripts provided by the developers mentioned above. However, when I tried to convert it into a DPGEN input file, I still encountered an error. Can you help me see where the problem lies? Thank you very much！ --- You are parsing data using package Cp2kData --- You are reading cell information from ./aimd/output Obtian Energies From ./aimd/input-1.ener Obtian Structures From ./aimd/input-pos-1.xyz Obtian Froces From ./aimd/input-frc-1.xyz Atom names are fake chemical symbols as you set in cp2k input. --- You are parsing data using package Cp2kData --- Data Summary Labeled System Frame Numbers : 21 Atom Numbers : 489 Including Virials : No Element List : Au S C H 35 18 224 212
> 
> the data contains 21 frames

please show the error.

**Comment by chenyuping6** [comment]
> > Hi I am able to successfully convert the cp2k md file into a DP model using the scripts provided by the developers mentioned above. However, when I tried to convert it into a DPGEN input file, I still encountered an error. Can you help me see where the problem lies? Thank you very much！ --- You are parsing data using package Cp2kData --- You are reading cell information from ./aimd/output Obtian Energies From ./aimd/input-1.ener Obtian Structures From ./aimd/input-pos-1.xyz Obtian Froces From ./aimd/input-frc-1.xyz Atom names are fake chemical symbols as you set in cp2k input. --- You are parsing data using package Cp2kData --- Data Summary Labeled System Frame Numbers : 21 Atom Numbers : 489 Including Virials : No Element List : Au S C H 35 18 224 212
> > the data contains 21 frames
> 
> please show the error.

I'm sorry, the above is all the output information. There were no additional errors, but there was no conversion result either.

**Comment by chenyuping6** [comment]
> > Hi I am able to successfully convert the cp2k md file into a DP model using the scripts provided by the developers mentioned above. However, when I tried to convert it into a DPGEN input file, I still encountered an error. Can you help me see where the problem lies? Thank you very much！ --- You are parsing data using package Cp2kData --- You are reading cell information from ./aimd/output Obtian Energies From ./aimd/input-1.ener Obtian Structures From ./aimd/input-pos-1.xyz Obtian Froces From ./aimd/input-frc-1.xyz Atom names are fake chemical symbols as you set in cp2k input. --- You are parsing data using package Cp2kData --- Data Summary Labeled System Frame Numbers : 21 Atom Numbers : 489 Including Virials : No Element List : Au S C H 35 18 224 212
> > the data contains 21 frames
> 
> please show the error.

I'm sorry, the above is all the output information. There were no additional errors, but there was no conversion result either.
The command I entered is：
import dpdata
from cp2kdata import Cp2kOutput
import numpy as np

cp2kmd_dir = "aimd"
cp2kmd_output_name = "output"
data = dpdata.LabeledSystem('./aimd', cp2k_output_name='output', fmt="cp2kdata/md")
print(data)

**Comment by robinzyb** [comment]
Sorry, there is no error according to your message. I don't understand why you have errors.

**Comment by chenyuping6** [comment]
> Sorry, there is no error according to your message. I don't understand why you have errors.

Thank you for your reply. Also, can I use training data as the input file for dpgen?

**Comment by robinzyb** [comment]
> > Sorry, there is no error according to your message. I don't understand why you have errors.
> 
> Thank you for your reply. Also, can I use training data as the input file for dpgen?

https://docs.deepmodeling.com/projects/dpgen/en/latest/run/param.html#argument:run_jdata/init_data_sys

**Comment by chenyuping6** [comment]
> Received. My problem is solved now. Thank you very much!

I have received it. Thank you very much!
